ui_modulesubdir = join_paths(moduledir, 'ui')

ui_sources = [
  '__init__.py',
  'host_editor.py',
  'host_list.py',
  'main_window.py',
  'preferences_dialog.py',
  'test_connection_dialog.py',
  'ssh_key_manager_dialog.py',
  'generate_key_dialog.py',
  'key_picker_dialog.py',
  'keyboard_shortcuts_dialog.py',
  'welcome_view.py',
]

install_data(ui_sources, install_dir: ui_modulesubdir)

